### ISSUE TITLE
DeprecationWarning: Ftp.raw[user](args): Use Ftp.raw('user args') instead.

### ISSUE THREAD

**Issue by SuThaw** [sergi/jsftp#226] opened 2017-02-02 06:00 UTC
When I use ftp.auth method,  this deprecation warning appear. is there anyway to do authentication. my code is following.
```
const connect = (server) => new Promise((resolve,reject)=>{
	
	// create new ftp server with r	
	const ftp = new JSFtp({
		host: server.host,
		port: server.port || 21,
		user: server.user,
		pass: server.pass,
		debugMode: true
	});	
		

	ftp.on('error',function(err){
		if(err.code == 530 ) reject({status: true, err: 'invalid user credential'});
		if(err.code == 'ENOTFOUND') reject({status: true, err: 'invalid host'});
		reject({status: true,err:'criteria is not correct. cannot connect to server' });
	});

	ftp.on('connect',function(err){
		
		ftp
			.auth(server.user,server.pass,(err,data) => {
				if(err)	reject({ status: true, err: 'Error: 530 Login incorrect'});

				resolve(ftp);
			})
		// resolve(ftp);
	})
});

**Comment by joaopedroft** [comment] 2017-02-05 18:31
It happens the same with me :(

**Comment by svenbw** [comment] 2017-02-08 13:40
This is caused by the auth function itself for user [look at line 334](https://github.com/sergi/jsftp/blob/v1.5.5/lib/jsftp.js#L334), for password its [line 340](https://github.com/sergi/jsftp/blob/v1.5.5/lib/jsftp.js#L340) and for type it's [line 349](https://github.com/sergi/jsftp/blob/v1.5.5/lib/jsftp.js#L349).
They should be changed to `self.raw('user ' + user, function(...`, `self.raw('pass' + pass, function(...` and `self.raw('type I', function(...`.

**Comment by marcelorisse** [comment] 2017-02-24 20:57
This was already fixed and it is merged on master: https://github.com/sergi/jsftp/commit/35a8edd6e1132898590d585a415c521df000cb58. Could anyone release a new version so we stop receiving these warnings, please?

**Comment by leizhao4** [comment] 2017-03-11 07:15
Bump. Can we have a new release, please?

**Comment by julmot** [comment] 2017-03-12 18:30
Receiving this warning too. Bump.

**Comment by daniel-johnson** [comment] 2017-03-22 23:00
Receiving. Bump it up!

**Comment by adamgedney** [comment] 2017-03-31 13:57
Same here

**Comment by simonh1000** [comment] 2017-05-02 19:05
Although this has been closed the lines referred to by @svenbw remain unaltered in the version distributed via npm. I think the new code needs to be `npm publish`ed

**Comment by leizhao4** [comment] 2017-05-02 19:08
Bump @sergi

**Comment by kunokdev** [comment] 2017-05-03 10:16
+1, are moderators of this library active or should we fork ?

**Comment by juampi92** [comment] 2017-05-08 23:46
Guys, it's just a simple push to npm publish.... please

**Comment by simonh1000** [comment] 2017-05-14 14:44
Bump @sergi

**Comment by littledu** [comment] 2017-05-15 08:57
Guys, it's just a simple push to npm publish.... please

**Comment by hk95** [comment] 2017-05-22 20:39
Bump @sergi

**Comment by jazoom** [comment] 2017-05-24 05:29
It's been a couple of months now. Is there a fork of this library that will be kept updated going forward?

**Comment by sergi** [comment] 2017-06-08 10:57
Released v2.0.0. Really sorry for the wait, personal stuff got in the way.

**Closed by sergi** 2017-06-08 10:57 UTC

**Comment by hk95** [comment] 2017-06-08 11:09
Thank you so much for the update, @sergi.
